camera/horizontal_fov: 90.0
camera/vertical_fov: 73.73

raycast/dr:     0.1
raycast/dphi:   10
raycast/dtheta: 10

system/bbx/r: 0.3
system/bbx/overshoot: 0.25

aep/gain/r_min: 0
aep/gain/r_max: 5
aep/gain/zero: 1
aep/gain/lambda: 0.75
aep/gain/sigma_thresh: 0.2
aep/tree/extension_range: 1.5
aep/tree/max_sampling_radius: 10
aep/tree/initial_iterations: 15
aep/tree/cutoff_iterations: 30

rrt/min_nodes: 400

# bounding box: necessary to limit the simulation
# scenario (smaller than actual gazebo scenario)
boundary/min: [-12.5, -12.5, 0.0]
boundary/max: [ 12.5,  12.5, 4.]


boundary/eval/min: [-12.5, -12.5, 0.0]
boundary/eval/max: [ 12.5,  12.5, 4.6]

#octomap_server/occupancy_min_z: 0.0
#octomap_server/occupancy_max_z: 2.0
octomap_server/sensor_model/hit: 0.7
octomap_server/sensor_model/miss: 0.4
octomap_server/sensor_model/min: 0.3
octomap_server/sensor_model/max: 0.7
octomap_server/sensor_model/max_range: 5.
octomap_server/resolution: 0.1

visualize_rays: false
visualize_tree: true
visualize_exploration_area: true

robot_frame: "fcu"
world_frame: "map"
