camera/horizontal_fov: 115.0
camera/vertical_fov: 60

raycast/dr:     0.2
raycast/dphi:   10
raycast/dtheta: 10

system/bbx/r: 0.3
system/bbx/overshoot: 0.25

aep/gain/r_min: 0
aep/gain/r_max: 7
aep/gain/zero: 2
aep/gain/lambda: 0.75
aep/gain/sigma_thresh: 0.2
aep/tree/extension_range: 3.
aep/tree/max_sampling_radius: 10
aep/tree/initial_iterations: 15
aep/tree/cutoff_iterations: 50

rrt/min_nodes: 400

# bounding box: necessary to limit the simulation
# scenario (smaller than actual gazebo scenario)
boundary/min: [-16.5, -15.5, -0.3]
boundary/max: [ 16.5,  15.5, 25.7]

boundary/eval/min: [-16.5, -15.5, -0.3]
boundary/eval/max: [ 16.5,  15.5, 25.7]


#octomap_server/occupancy_min_z: 0.0
#octomap_server/occupancy_max_z: 2.0
octomap_server/sensor_model/hit: 0.7
octomap_server/sensor_model/miss: 0.4
octomap_server/sensor_model/min: 0.3
octomap_server/sensor_model/max: 0.7
octomap_server/sensor_model/max_range: 7.
octomap_server/resolution: 0.2

visualize_rays: false
visualize_tree: true
visualize_exploration_area: true

robot_frame: "fcu"
world_frame: "map"
